Correct `tiller_namespace` schema
This fixes https://github.com/djhaskin987/terraform-provider-helmcmd/pull/2.

`terraform apply` before this change:
```
  Error: provider.helmcmd: Internal validation of the provider failed! This is always a bug
  with the provider itself, and not a user issue. Please report
  this bug:

  1 error(s) occurred:

  * tiller_namespace: One of optional, required, or computed must be set
```